//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iec62325.351:tc57wg16:451-1:acknowledgementdocument:7:0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iec62325.351:tc57wg16:451-1:acknowledgementdocument:7:0", IsNullable=false)]
public partial class Acknowledgement_MarketDocument {
    
    private string mRIDField;
    
    private string createdDateTimeField;
    
    private string sender_MarketParticipantmarketRoletypeField;
    
    private string receiver_MarketParticipantmarketRoletypeField;
    
    private string received_MarketDocumentcreatedDateTimeField;
    
    private Acknowledgement_MarketDocumentSender_MarketParticipantmRID[] sender_MarketParticipantmRIDField;
    
    private Acknowledgement_MarketDocumentReceiver_MarketParticipantmRID[] receiver_MarketParticipantmRIDField;
    
    private Acknowledgement_MarketDocumentReason[] reasonField;
    
    /// <remarks/>
    public string mRID {
        get {
            return this.mRIDField;
        }
        set {
            this.mRIDField = value;
        }
    }
    
    /// <remarks/>
    public string createdDateTime {
        get {
            return this.createdDateTimeField;
        }
        set {
            this.createdDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sender_MarketParticipant.marketRole.type")]
    public string sender_MarketParticipantmarketRoletype {
        get {
            return this.sender_MarketParticipantmarketRoletypeField;
        }
        set {
            this.sender_MarketParticipantmarketRoletypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("receiver_MarketParticipant.marketRole.type")]
    public string receiver_MarketParticipantmarketRoletype {
        get {
            return this.receiver_MarketParticipantmarketRoletypeField;
        }
        set {
            this.receiver_MarketParticipantmarketRoletypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("received_MarketDocument.createdDateTime")]
    public string received_MarketDocumentcreatedDateTime {
        get {
            return this.received_MarketDocumentcreatedDateTimeField;
        }
        set {
            this.received_MarketDocumentcreatedDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sender_MarketParticipant.mRID", IsNullable=true)]
    public Acknowledgement_MarketDocumentSender_MarketParticipantmRID[] sender_MarketParticipantmRID {
        get {
            return this.sender_MarketParticipantmRIDField;
        }
        set {
            this.sender_MarketParticipantmRIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("receiver_MarketParticipant.mRID", IsNullable=true)]
    public Acknowledgement_MarketDocumentReceiver_MarketParticipantmRID[] receiver_MarketParticipantmRID {
        get {
            return this.receiver_MarketParticipantmRIDField;
        }
        set {
            this.receiver_MarketParticipantmRIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reason")]
    public Acknowledgement_MarketDocumentReason[] Reason {
        get {
            return this.reasonField;
        }
        set {
            this.reasonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iec62325.351:tc57wg16:451-1:acknowledgementdocument:7:0")]
public partial class Acknowledgement_MarketDocumentSender_MarketParticipantmRID {
    
    private string codingSchemeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codingScheme {
        get {
            return this.codingSchemeField;
        }
        set {
            this.codingSchemeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iec62325.351:tc57wg16:451-1:acknowledgementdocument:7:0")]
public partial class Acknowledgement_MarketDocumentReceiver_MarketParticipantmRID {
    
    private string codingSchemeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codingScheme {
        get {
            return this.codingSchemeField;
        }
        set {
            this.codingSchemeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iec62325.351:tc57wg16:451-1:acknowledgementdocument:7:0")]
public partial class Acknowledgement_MarketDocumentReason {
    
    private string codeField;
    
    private string textField;
    
    /// <remarks/>
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iec62325.351:tc57wg16:451-1:acknowledgementdocument:7:0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iec62325.351:tc57wg16:451-1:acknowledgementdocument:7:0", IsNullable=false)]
public partial class NewDataSet {
    
    private Acknowledgement_MarketDocument[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Acknowledgement_MarketDocument")]
    public Acknowledgement_MarketDocument[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
